language: node_js

node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm i -g yarn

install:
  - yarn install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - yarn --cwd api/ build
  - yarn --cwd models/ build

test:
  - yarn test

env:
  - CXX=g++-4.8

services: 
  - mongodb

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8