language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run build
  - npm run start

test:
  - npm test

env:
  - CXX=g++-4.8

services: 
  - mongodb

addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8